# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_4; end
module ::Anonymous_Delegator_5; end
module ActiveRecord::CollectionCacheKey; end
